### ISSUE TITLE
unitialized constant Win32::EventLog::INFO

### ISSUE THREAD

**Issue by juliandunn** [jtimberman/eventlog-cookbook#2]
This has started happening... need to find out why.

```
ERROR: Report handler Opscode::ReportEventLog raised #<NameError: uninitialized constant Win32::EventLog::INFO>
ERROR: c:/chef/handlers/win32_eventlog_handler.rb:30:in `report'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/handler.rb:226:in `run_report_unsafe'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/handler.rb:214:in `run_report_safely'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/handler.rb:93:in `block in run_report_handlers'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/handler.rb:92:in `each'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/handler.rb:92:in `run_report_handlers'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/handler.rb:103:in `block in <class:Handler>'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/client.rb:113:in `call'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/client.rb:113:in `block in run_completed_successfully'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/client.rb:112:in `each'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/client.rb:112:in `run_completed_successfully'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/client.rb:506:in `do_run'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/client.rb:213:in `run'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/application.rb:208:in `run_chef_client'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/application/client.rb:312:in `block in run_application'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/application/client.rb:304:in `loop'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/application/client.rb:304:in `run_application'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/lib/chef/application.rb:66:in `run'
ERROR: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2-x86-mingw32/bin/chef-client:26:in `<top (required)>'
ERROR: C:/opscode/chef/bin/chef-client:23:in `load'
ERROR: C:/opscode/chef/bin/chef-client:23:in `<main>'
INFO: Report handlers complete
```

**Comment by jtimberman** [comment]
Upstream in the gem perhaps?

**Comment by juliandunn** [comment]
Probably, this was more of a reminder for me to figure out WTF is going on :)
